Website_visitor.xlsx  dataset mimics the demographic information for the imaginary website, and all the data present in it is made up. It's fake data. And this data set has been designed in such a way that we can cover most of the challenges(not all!) that is faced while cleaning data for machine learning or analytics. Like missing values, we have many missing values. And also we have incorrect values like in age, we see that the date format is not right for some entries. We will be performing data quality checks,  identifying the problems in our data, like whether our data has missing values, duplicate values, or some other kind of issues.


make sure that you apply all the modification to the same dataframe and save it after finishing

In [3]:
# find the path of the folder of your codes in your computer
import os
os.getcwd()

'C:\\Users\\lujai\\information th'

In [5]:
import pandas as pd# مكتبة توفر أدوات للعمل مع البيانات المهيكلة مثل الجداول ومعالجتها في داتا فريم
import numpy as np
from sklearn.impute import SimpleImputer#يستخدم لايجاد القيم المفقودة في البيانات.يمكنك استخدامه لاستبدال القيم المفقودة بمتوسط أو وسيط أو أكثر القيم تكرارًا أو قيمة ثابتة
from scipy import stats#توفر مجموعة واسعة من الدوال الإحصائية
from sklearn.preprocessing import MinMaxScaler# تحسين اداء النماذج و توسيع نطاق البيانات حيث تكون بين 0و1

In [6]:
raw_data = pd.read_excel('website_visitors.xlsx')#يقرى الملف ويسوي داتا فريم

In [7]:
raw_data.head()

,customer_id,date,age,gender,country,item purchased,value,monthly visits
0,1,2022-03-02 00:00:00,23,Male,US,2.0,258,234
1,1,2022-03-02 00:00:00,23,Male,US,2.0,258,234
2,2,2022-03-03 00:00:00,34,Female,India,5.0,645,567
3,3,2022-03-04 00:00:00,23,Male,NaN,2.0,258,123
4,4,2022-03-05 00:00:00,ERR,Male,UK,7.0,903,123

In [8]:
# This method removes duplicate rows from the DataFrame. By default, it keeps the first occurrence of the duplicate row and removes any subsequent duplicates.
# Drop duplicate rows in place (modifies the original DataFrame): raw_data.drop_duplicates(inplace=True)
raw_data = raw_data.drop_duplicates()

In [9]:
raw_data

,customer_id,date,age,gender,country,item purchased,value,monthly visits
0,1,2022-03-02 00:00:00,23,Male,US,2.0,258,234
2,2,2022-03-03 00:00:00,34,Female,India,5.0,645,567
3,3,2022-03-04 00:00:00,23,Male,NaN,2.0,258,123
4,4,2022-03-05 00:00:00,ERR,Male,UK,7.0,903,123
5,5,2021-03-23 00:00:00,23,Male,France,1.0,129,47
6,6,2022-03-07 00:00:00,NaN,Male,Bolivia,9.0,1161,3
7,7,2022-03-08 00:00:00,27,Male,Sweden,2.0,258,557
8,8,2021-02-02 00:00:00,23,Male,USA,1.0,129,455
9,9,2022-03-10 00:00:00,29,Female,Germany,2.0,258,NaN
10,10,2022-03-11 00:00:00,21,Male,Germany,6.0,774,554
11,11,2022-03-12 00:00:00,NaN,Male,Brazil,5.0,645,397
12,12,2022-03-13 00:00:00,31,Female,USA,4.0,516,567
13,13,2022-03-14 00:00:00,32,Male,India,2.0,258,347
14,14,3-15-21,27,Male,Chile,3.0,387,NaN
15,15,2022-03-16 00:00:00,23,Female,Saudi Arabia,6.0,774,582
16,16,2022-03-17 00:00:00,26,Male,India,7.0,903,234
17,17,2022-03-18 00:00:00,29,Female,Chile,9.0,1161,ERR
18,18,2022-03-19 00:00:00,ERR,Male,Saudi Arabia,1.0,129,234
19,19,2022-03-20 00:00:00,35,Male,India,6.0,774,478
20,20,2022-03-21 00:00:00,38,Female,US,2.0,258,490
21,21,2022-03-22 00:00:00,41,Male,US,7.0,903,234
22,22,2022-03-23 00:00:00,44,Female,Japan,5.0,645,234
23,23,2022-03-24 00:00:00,NaN,Male,US,3.0,387,345
24,24,2022-03-25 00:00:00,23,Male,Norway,3.0,387,678
25,25,2022-03-26 00:00:00,21,Female,Spain,NaN,67,NaN
26,26,2022-03-27 00:00:00,26,Male,Chile,4.0,516,109
27,27,2022-03-28 00:00:00,23,NaN,Nigeria,2.0,258,756
28,28,2022-03-29 00:00:00,27,Male,United Kingdom,3.0,387,390
29,29,2022-03-30 00:00:00,34,Male,Switzerland,3.0,387,268
30,30,2022-03-31 00:00:00,27,Female,Russia,3.0,387,235

In [10]:
raw_data = raw_data.replace('ERR',np.nan)

In [11]:
raw_data

,customer_id,date,age,gender,country,item purchased,value,monthly visits
0,1,2022-03-02 00:00:00,23.0,Male,US,2.0,258,234.0
2,2,2022-03-03 00:00:00,34.0,Female,India,5.0,645,567.0
3,3,2022-03-04 00:00:00,23.0,Male,NaN,2.0,258,123.0
4,4,2022-03-05 00:00:00,NaN,Male,UK,7.0,903,123.0
5,5,2021-03-23 00:00:00,23.0,Male,France,1.0,129,47.0
6,6,2022-03-07 00:00:00,NaN,Male,Bolivia,9.0,1161,3.0
7,7,2022-03-08 00:00:00,27.0,Male,Sweden,2.0,258,557.0
8,8,2021-02-02 00:00:00,23.0,Male,USA,1.0,129,455.0
9,9,2022-03-10 00:00:00,29.0,Female,Germany,2.0,258,NaN
10,10,2022-03-11 00:00:00,21.0,Male,Germany,6.0,774,554.0
11,11,2022-03-12 00:00:00,NaN,Male,Brazil,5.0,645,397.0
12,12,2022-03-13 00:00:00,31.0,Female,USA,4.0,516,567.0
13,13,2022-03-14 00:00:00,32.0,Male,India,2.0,258,347.0
14,14,3-15-21,27.0,Male,Chile,3.0,387,NaN
15,15,2022-03-16 00:00:00,23.0,Female,Saudi Arabia,6.0,774,582.0
16,16,2022-03-17 00:00:00,26.0,Male,India,7.0,903,234.0
17,17,2022-03-18 00:00:00,29.0,Female,Chile,9.0,1161,NaN
18,18,2022-03-19 00:00:00,NaN,Male,Saudi Arabia,1.0,129,234.0
19,19,2022-03-20 00:00:00,35.0,Male,India,6.0,774,478.0
20,20,2022-03-21 00:00:00,38.0,Female,US,2.0,258,490.0
21,21,2022-03-22 00:00:00,41.0,Male,US,7.0,903,234.0
22,22,2022-03-23 00:00:00,44.0,Female,Japan,5.0,645,234.0
23,23,2022-03-24 00:00:00,NaN,Male,US,3.0,387,345.0
24,24,2022-03-25 00:00:00,23.0,Male,Norway,3.0,387,678.0
25,25,2022-03-26 00:00:00,21.0,Female,Spain,NaN,67,NaN
26,26,2022-03-27 00:00:00,26.0,Male,Chile,4.0,516,109.0
27,27,2022-03-28 00:00:00,23.0,NaN,Nigeria,2.0,258,756.0
28,28,2022-03-29 00:00:00,27.0,Male,United Kingdom,3.0,387,390.0
29,29,2022-03-30 00:00:00,34.0,Male,Switzerland,3.0,387,268.0
30,30,2022-03-31 00:00:00,27.0,Female,Russia,3.0,387,235.0

In [12]:
# SimpleImputer: This is a class from the sklearn.impute module in the scikit-learn library, used for handling missing data. It fills in missing values with a specified strategy.
# missing_values=np.nan: Specifies that the imputer should look for missing values in the dataset that are represented by np.nan (which is the representation for missing or "Not a Number" values in numpy).
# strategy='mean': Defines the imputation strategy. In this case, the imputer will calculate the mean of the non-missing values in a column and replace all the missing values (np.nan) in that column with the computed mean.

imputer = SimpleImputer(missing_values = np.nan,strategy = 'mean') # يحدد وش هي الميسينق وكيف الاستراتيجية الي حنتبعها وحددنا المين لان في قيم متطرفة

In [14]:
#selects the three columns ['value', 'item purchased', 'monthly visits'] from the raw_data DataFrame where missing values will be imputed.
# imputer.fit_transform(): Performs both the fitting (calculating the mean for each column) and transformation (replacing missing values with the mean) in one step.

raw_data[['value','item purchased','monthly visits']]=imputer.fit_transform(raw_data[['value','item purchased','monthly visits']])#  تقوم بمعالجة القيم المفقودة في الأعمدة المحددة

In [15]:
raw_data

,customer_id,date,age,gender,country,item purchased,value,monthly visits
0,1,2022-03-02 00:00:00,23.0,Male,US,2.000000,258.0,234.000000
2,2,2022-03-03 00:00:00,34.0,Female,India,5.000000,645.0,567.000000
3,3,2022-03-04 00:00:00,23.0,Male,NaN,2.000000,258.0,123.000000
4,4,2022-03-05 00:00:00,NaN,Male,UK,7.000000,903.0,123.000000
5,5,2021-03-23 00:00:00,23.0,Male,France,1.000000,129.0,47.000000
6,6,2022-03-07 00:00:00,NaN,Male,Bolivia,9.000000,1161.0,3.000000
7,7,2022-03-08 00:00:00,27.0,Male,Sweden,2.000000,258.0,557.000000
8,8,2021-02-02 00:00:00,23.0,Male,USA,1.000000,129.0,455.000000
9,9,2022-03-10 00:00:00,29.0,Female,Germany,2.000000,258.0,355.423077
10,10,2022-03-11 00:00:00,21.0,Male,Germany,6.000000,774.0,554.000000
11,11,2022-03-12 00:00:00,NaN,Male,Brazil,5.000000,645.0,397.000000
12,12,2022-03-13 00:00:00,31.0,Female,USA,4.000000,516.0,567.000000
13,13,2022-03-14 00:00:00,32.0,Male,India,2.000000,258.0,347.000000
14,14,3-15-21,27.0,Male,Chile,3.000000,387.0,355.423077
15,15,2022-03-16 00:00:00,23.0,Female,Saudi Arabia,6.000000,774.0,582.000000
16,16,2022-03-17 00:00:00,26.0,Male,India,7.000000,903.0,234.000000
17,17,2022-03-18 00:00:00,29.0,Female,Chile,9.000000,1161.0,355.423077
18,18,2022-03-19 00:00:00,NaN,Male,Saudi Arabia,1.000000,129.0,234.000000
19,19,2022-03-20 00:00:00,35.0,Male,India,6.000000,774.0,478.000000
20,20,2022-03-21 00:00:00,38.0,Female,US,2.000000,258.0,490.000000
21,21,2022-03-22 00:00:00,41.0,Male,US,7.000000,903.0,234.000000
22,22,2022-03-23 00:00:00,44.0,Female,Japan,5.000000,645.0,234.000000
23,23,2022-03-24 00:00:00,NaN,Male,US,3.000000,387.0,345.000000
24,24,2022-03-25 00:00:00,23.0,Male,Norway,3.000000,387.0,678.000000
25,25,2022-03-26 00:00:00,21.0,Female,Spain,3.965517,67.0,355.423077
26,26,2022-03-27 00:00:00,26.0,Male,Chile,4.000000,516.0,109.000000
27,27,2022-03-28 00:00:00,23.0,NaN,Nigeria,2.000000,258.0,756.000000
28,28,2022-03-29 00:00:00,27.0,Male,United Kingdom,3.000000,387.0,390.000000
29,29,2022-03-30 00:00:00,34.0,Male,Switzerland,3.000000,387.0,268.000000
30,30,2022-03-31 00:00:00,27.0,Female,Russia,3.000000,387.0,235.000000

In [17]:
# dropna(): This method is used to remove rows (or columns) that contain missing values (NaN) from a pandas DataFrame.
raw_data.dropna(inplace=True)

In [27]:
raw_data

,customer_id,date,age,gender,country,item purchased,value,monthly visits
0,1,2022-03-02 00:00:00,23.0,Male,US,2.000000,258.0,234.000000
2,2,2022-03-03 00:00:00,34.0,Female,India,5.000000,645.0,567.000000
5,5,2021-03-23 00:00:00,23.0,Male,France,1.000000,129.0,47.000000
7,7,2022-03-08 00:00:00,27.0,Male,Sweden,2.000000,258.0,557.000000
8,8,2021-02-02 00:00:00,23.0,Male,USA,1.000000,129.0,455.000000
9,9,2022-03-10 00:00:00,29.0,Female,Germany,2.000000,258.0,355.423077
10,10,2022-03-11 00:00:00,21.0,Male,Germany,6.000000,774.0,554.000000
12,12,2022-03-13 00:00:00,31.0,Female,USA,4.000000,516.0,567.000000
13,13,2022-03-14 00:00:00,32.0,Male,India,2.000000,258.0,347.000000
14,14,3-15-21,27.0,Male,Chile,3.000000,387.0,355.423077
15,15,2022-03-16 00:00:00,23.0,Female,Saudi Arabia,6.000000,774.0,582.000000
16,16,2022-03-17 00:00:00,26.0,Male,India,7.000000,903.0,234.000000
17,17,2022-03-18 00:00:00,29.0,Female,Chile,9.000000,1161.0,355.423077
19,19,2022-03-20 00:00:00,35.0,Male,India,6.000000,774.0,478.000000
20,20,2022-03-21 00:00:00,38.0,Female,US,2.000000,258.0,490.000000
21,21,2022-03-22 00:00:00,41.0,Male,US,7.000000,903.0,234.000000
22,22,2022-03-23 00:00:00,44.0,Female,Japan,5.000000,645.0,234.000000
24,24,2022-03-25 00:00:00,23.0,Male,Norway,3.000000,387.0,678.000000
25,25,2022-03-26 00:00:00,21.0,Female,Spain,3.965517,67.0,355.423077
26,26,2022-03-27 00:00:00,26.0,Male,Chile,4.000000,516.0,109.000000
28,28,2022-03-29 00:00:00,27.0,Male,United Kingdom,3.000000,387.0,390.000000
29,29,2022-03-30 00:00:00,34.0,Male,Switzerland,3.000000,387.0,268.000000
30,30,2022-03-31 00:00:00,27.0,Female,Russia,3.000000,387.0,235.000000

In [28]:
# .str.strip(): This is a pandas string method used to remove leading and trailing whitespace characters from each value in the 'gender' column
raw_data['gender']=raw_data['gender'].str.strip()
raw_data['country']=raw_data['country'].str.strip()

In [31]:
raw_data

,customer_id,date,age,gender,country,item purchased,value,monthly visits
0,1,2022-03-02 00:00:00,23.0,Male,US,2.000000,258.0,234.000000
2,2,2022-03-03 00:00:00,34.0,Female,India,5.000000,645.0,567.000000
5,5,2021-03-23 00:00:00,23.0,Male,France,1.000000,129.0,47.000000
7,7,2022-03-08 00:00:00,27.0,Male,Sweden,2.000000,258.0,557.000000
8,8,2021-02-02 00:00:00,23.0,Male,USA,1.000000,129.0,455.000000
9,9,2022-03-10 00:00:00,29.0,Female,Germany,2.000000,258.0,355.423077
10,10,2022-03-11 00:00:00,21.0,Male,Germany,6.000000,774.0,554.000000
12,12,2022-03-13 00:00:00,31.0,Female,USA,4.000000,516.0,567.000000
13,13,2022-03-14 00:00:00,32.0,Male,India,2.000000,258.0,347.000000
14,14,3-15-21,27.0,Male,Chile,3.000000,387.0,355.423077
15,15,2022-03-16 00:00:00,23.0,Female,Saudi Arabia,6.000000,774.0,582.000000
16,16,2022-03-17 00:00:00,26.0,Male,India,7.000000,903.0,234.000000
17,17,2022-03-18 00:00:00,29.0,Female,Chile,9.000000,1161.0,355.423077
19,19,2022-03-20 00:00:00,35.0,Male,India,6.000000,774.0,478.000000
20,20,2022-03-21 00:00:00,38.0,Female,US,2.000000,258.0,490.000000
21,21,2022-03-22 00:00:00,41.0,Male,US,7.000000,903.0,234.000000
22,22,2022-03-23 00:00:00,44.0,Female,Japan,5.000000,645.0,234.000000
24,24,2022-03-25 00:00:00,23.0,Male,Norway,3.000000,387.0,678.000000
25,25,2022-03-26 00:00:00,21.0,Female,Spain,3.965517,67.0,355.423077
26,26,2022-03-27 00:00:00,26.0,Male,Chile,4.000000,516.0,109.000000
28,28,2022-03-29 00:00:00,27.0,Male,United Kingdom,3.000000,387.0,390.000000
29,29,2022-03-30 00:00:00,34.0,Male,Switzerland,3.000000,387.0,268.000000
30,30,2022-03-31 00:00:00,27.0,Female,Russia,3.000000,387.0,235.000000

In [33]:
raw_data.info()#يتضمن معلومات حول عدد الصفوف والأعمدة، أسماء الأعمدة، نوع البيانات لكل عمود، وعدد القيم غير المفقودة في كل عمود

<class 'pandas.core.frame.DataFrame'>
Index: 23 entries, 0 to 30
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     23 non-null     int64
 1   date            23 non-null     object
 2   age             23 non-null     float64
 3   gender          23 non-null     object
 4   country         23 non-null     object
 5   item purchased  23 non-null     float64
 6   value           23 non-null     float64
 7   monthly visits  23 non-null     float64
dtypes: float64(4), int64(1), object(3)
memory usage: 1.6+ KB

In [35]:

# It takes the column 'date' from the raw_data DataFrame, which may contain strings, integers, or other formats representing dates, and converts it to pandas' datetime format.
# The function pd.to_datetime() attempts to interpret the values in the column as dates and times, converting them into pandas' internal datetime64 format, which is efficient and allows for various date-related operations (like filtering, sorting, or extracting specific components such as the year or month).

raw_data['date']=pd.to_datetime(raw_data['date'])

In [37]:
raw_data

,customer_id,date,age,gender,country,item purchased,value,monthly visits
0,1,2022-03-02,23.0,Male,US,2.000000,258.0,234.000000
2,2,2022-03-03,34.0,Female,India,5.000000,645.0,567.000000
5,5,2021-03-23,23.0,Male,France,1.000000,129.0,47.000000
7,7,2022-03-08,27.0,Male,Sweden,2.000000,258.0,557.000000
8,8,2021-02-02,23.0,Male,USA,1.000000,129.0,455.000000
9,9,2022-03-10,29.0,Female,Germany,2.000000,258.0,355.423077
10,10,2022-03-11,21.0,Male,Germany,6.000000,774.0,554.000000
12,12,2022-03-13,31.0,Female,USA,4.000000,516.0,567.000000
13,13,2022-03-14,32.0,Male,India,2.000000,258.0,347.000000
14,14,2021-03-15,27.0,Male,Chile,3.000000,387.0,355.423077
15,15,2022-03-16,23.0,Female,Saudi Arabia,6.000000,774.0,582.000000
16,16,2022-03-17,26.0,Male,India,7.000000,903.0,234.000000
17,17,2022-03-18,29.0,Female,Chile,9.000000,1161.0,355.423077
19,19,2022-03-20,35.0,Male,India,6.000000,774.0,478.000000
20,20,2022-03-21,38.0,Female,US,2.000000,258.0,490.000000
21,21,2022-03-22,41.0,Male,US,7.000000,903.0,234.000000
22,22,2022-03-23,44.0,Female,Japan,5.000000,645.0,234.000000
24,24,2022-03-25,23.0,Male,Norway,3.000000,387.0,678.000000
25,25,2022-03-26,21.0,Female,Spain,3.965517,67.0,355.423077
26,26,2022-03-27,26.0,Male,Chile,4.000000,516.0,109.000000
28,28,2022-03-29,27.0,Male,United Kingdom,3.000000,387.0,390.000000
29,29,2022-03-30,34.0,Male,Switzerland,3.000000,387.0,268.000000
30,30,2022-03-31,27.0,Female,Russia,3.000000,387.0,235.000000

In [39]:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23 entries, 0 to 30
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     23 non-null     int64
 1   date            23 non-null     datetime64[ns]
 2   age             23 non-null     float64
 3   gender          23 non-null     object
 4   country         23 non-null     object
 5   item purchased  23 non-null     float64
 6   value           23 non-null     float64
 7   monthly visits  23 non-null     float64
dtypes: datetime64[ns](1), float64(4), int64(1), object(2)
memory usage: 1.6+ KB

In [41]:
# the astype(int) method is used to convert the data type of the elements in the column to integer (int). If the column contains any non-integer values (such as floats or strings), this will attempt to convert them to integers.
raw_data['age']=raw_data['age'].astype(int)

# the astype(str) method is used to convert the data type of the elements in the column to string
#raw_data['country'] = raw_data['country'].astype(str)

In [43]:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23 entries, 0 to 30
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     23 non-null     int64
 1   date            23 non-null     datetime64[ns]
 2   age             23 non-null     int32
 3   gender          23 non-null     object
 4   country         23 non-null     object
 5   item purchased  23 non-null     float64
 6   value           23 non-null     float64
 7   monthly visits  23 non-null     float64
dtypes: datetime64[ns](1), float64(3), int32(1), int64(1), object(2)
memory usage: 1.5+ KB

In [45]:
raw_data.head()#----------------------------------------------------------------------------------------------------

,customer_id,date,age,gender,country,item purchased,value,monthly visits
0,1,2022-03-02,23,Male,US,2.0,258.0,234.0
2,2,2022-03-03,34,Female,India,5.0,645.0,567.0
5,5,2021-03-23,23,Male,France,1.0,129.0,47.0
7,7,2022-03-08,27,Male,Sweden,2.0,258.0,557.0
8,8,2021-02-02,23,Male,USA,1.0,129.0,455.0

In [47]:
raw_data['country'].unique()

array(['US', 'India', 'France', 'Sweden', 'USA', 'Germany', 'Chile',
       'Saudi Arabia', 'Japan', 'Norway', 'Spain', 'United Kingdom',
       'Switzerland', 'Russia'], dtype=object)

In [49]:
raw_data['country']=raw_data['country'].replace('USA','US')

In [51]:
raw_data['country'].unique()

array(['US', 'India', 'France', 'Sweden', 'Germany', 'Chile',
       'Saudi Arabia', 'Japan', 'Norway', 'Spain', 'United Kingdom',
       'Switzerland', 'Russia'], dtype=object)

In [53]:
raw_data.head()

,customer_id,date,age,gender,country,item purchased,value,monthly visits
0,1,2022-03-02,23,Male,US,2.0,258.0,234.0
2,2,2022-03-03,34,Female,India,5.0,645.0,567.0
5,5,2021-03-23,23,Male,France,1.0,129.0,47.0
7,7,2022-03-08,27,Male,Sweden,2.0,258.0,557.0
8,8,2021-02-02,23,Male,US,1.0,129.0,455.0

In [55]:
# This line of code is used to map or convert categorical values in the gender column of the raw_data DataFrame to numerical values.
# 'Male' is replaced by 0.
# 'Female' is replaced by 1.

raw_data['gender'] = raw_data['gender'].map({'Male':0,'Female':1})

In [57]:
raw_data

,customer_id,date,age,gender,country,item purchased,value,monthly visits
0,1,2022-03-02,23,0,US,2.000000,258.0,234.000000
2,2,2022-03-03,34,1,India,5.000000,645.0,567.000000
5,5,2021-03-23,23,0,France,1.000000,129.0,47.000000
7,7,2022-03-08,27,0,Sweden,2.000000,258.0,557.000000
8,8,2021-02-02,23,0,US,1.000000,129.0,455.000000
9,9,2022-03-10,29,1,Germany,2.000000,258.0,355.423077
10,10,2022-03-11,21,0,Germany,6.000000,774.0,554.000000
12,12,2022-03-13,31,1,US,4.000000,516.0,567.000000
13,13,2022-03-14,32,0,India,2.000000,258.0,347.000000
14,14,2021-03-15,27,0,Chile,3.000000,387.0,355.423077
15,15,2022-03-16,23,1,Saudi Arabia,6.000000,774.0,582.000000
16,16,2022-03-17,26,0,India,7.000000,903.0,234.000000
17,17,2022-03-18,29,1,Chile,9.000000,1161.0,355.423077
19,19,2022-03-20,35,0,India,6.000000,774.0,478.000000
20,20,2022-03-21,38,1,US,2.000000,258.0,490.000000
21,21,2022-03-22,41,0,US,7.000000,903.0,234.000000
22,22,2022-03-23,44,1,Japan,5.000000,645.0,234.000000
24,24,2022-03-25,23,0,Norway,3.000000,387.0,678.000000
25,25,2022-03-26,21,1,Spain,3.965517,67.0,355.423077
26,26,2022-03-27,26,0,Chile,4.000000,516.0,109.000000
28,28,2022-03-29,27,0,United Kingdom,3.000000,387.0,390.000000
29,29,2022-03-30,34,0,Switzerland,3.000000,387.0,268.000000
30,30,2022-03-31,27,1,Russia,3.000000,387.0,235.000000

In [59]:
raw_data.head()

<class 'pandas.core.frame.DataFrame'>
Index: 23 entries, 0 to 30
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     23 non-null     int64
 1   date            23 non-null     datetime64[ns]
 2   age             23 non-null     int32
 3   gender          23 non-null     int64
 4   country         23 non-null     object
 5   item purchased  23 non-null     float64
 6   value           23 non-null     float64
 7   monthly visits  23 non-null     float64
dtypes: datetime64[ns](1), float64(3), int32(1), int64(2), object(1)
memory usage: 1.5+ KB

In [61]:
# This code is used to classify the values in the 'monthly visits' column of the raw_data DataFrame based on a threshold of 500, assigning each value to either a 'Normal' or 'Active' category
# The function classify(label) takes one argument label (which is the value from the 'monthly visits' column). If the label (i.e., monthly visits) is less than 500, the function returns 'Normal'. If the label is 500 or greater, it returns 'Active'.
# .apply(lambda x: classify(x)): The .apply() function applies the classify() function to each value in the 'monthly visits' column.
# The lambda x: classify(x) is an anonymous function that calls classify() for each value x in the column 'monthly visits'


def classify(label):
    if label<500:
        return 'Normal'
    else:i
        return 'Active'



raw_data['label']=raw_data['monthly visits'].apply(lambda x: classify(x))

In [63]:
raw_data.head()

,customer_id,date,age,gender,country,item purchased,value,monthly visits,label
0,1,2022-03-02,23,0,US,2.0,258.0,234.0,Normal
2,2,2022-03-03,34,1,India,5.0,645.0,567.0,Active
5,5,2021-03-23,23,0,France,1.0,129.0,47.0,Normal
7,7,2022-03-08,27,0,Sweden,2.0,258.0,557.0,Active
8,8,2021-02-02,23,0,US,1.0,129.0,455.0,Normal

In [65]:
# This code modifies the label column of the raw_data DataFrame by mapping specific string values to numeric values 
# the string 'Normal' is replaced with 0.
# The string 'Active' is replaced with 1.

raw_data['label']=raw_data['label'].map({'Normal':0,'Active':1})

In [88]:
raw_data.head()

,age,gender,item purchased,value,monthly visits,label,country_Chile,country_France,country_Germany,country_India,country_Japan,country_Norway,country_Russia,country_Saudi Arabia,country_Spain,country_Sweden,country_Switzerland,country_US,country_United Kingdom
0,23,0,2.0,258.0,234.0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
2,34,1,5.0,645.0,567.0,1,0,0,0,1,0,0,0,0,0,0,0,0,0
5,23,0,1.0,129.0,47.0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
7,27,0,2.0,258.0,557.0,1,0,0,0,0,0,0,0,0,0,1,0,0,0
8,23,0,1.0,129.0,455.0,0,0,0,0,0,0,0,0,0,0,0,0,1,0

In [69]:
# this code is using the pandas.get_dummies() function to convert the categorical variable country into a set of binary (0 or 1) indicator variables, also known as one-hot encoding.
#df = pd.get_dummies(df, dtype=int)

raw_data = pd.get_dummies(raw_data,columns=['country'], dtype=int)
#raw_data = pd.get_dummies(raw_data, columns=['country']).astype(int)

In [71]:
raw_data.head()

,customer_id,date,age,gender,item purchased,value,monthly visits,label,country_Chile,country_France,...,country_India,country_Japan,country_Norway,country_Russia,country_Saudi Arabia,country_Spain,country_Sweden,country_Switzerland,country_US,country_United Kingdom
0,1,2022-03-02,23,0,2.0,258.0,234.0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,2,2022-03-03,34,1,5.0,645.0,567.0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
5,5,2021-03-23,23,0,1.0,129.0,47.0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7,7,2022-03-08,27,0,2.0,258.0,557.0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
8,8,2021-02-02,23,0,1.0,129.0,455.0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [73]:
# This code is used for outlier detection and removal based on the Z-score method. It filters rows in the raw_data DataFrame that contain outliers in the columns specified by the out_list (i.e., value, monthly visits, and item purchased).
# This calculates the Z-score for each value in the columns specified in out_list. The Z-score measures how many standard deviations a data point is from the mean of its respective column.
# The Z-score is calculated as  z= (x-mu)/sigma
# Z-scores near 0 indicate values close to the mean, while larger absolute Z-scores indicate potential outliers.
# This condition filters the rows where the absolute Z-score is less than 3. A Z-score greater than 3 (or less than -3) typically indicates an outlier, as it means the data point is more than 3 standard deviations away from the mean.
# So, this filters out values that are within 3 standard deviations of the mean, retaining "normal" data points and excluding potential outliers.
# .all(axis=1): This ensures that the condition (absolute Z-score < 3) holds for all columns in out_list simultaneously. In other words, it keeps rows where all values in the selected columns have Z-scores below 3.
# If any column in a row has a Z-score greater than or equal to 3 (indicating a potential outlier), the entire row is excluded from raw_data.

out_list = ['value','monthly visits', 'item purchased']

raw_data = raw_data[(np.abs(stats.zscore(raw_data[out_list]))<3).all(axis=1)]

In [75]:
raw_data.head()

,customer_id,date,age,gender,item purchased,value,monthly visits,label,country_Chile,country_France,...,country_India,country_Japan,country_Norway,country_Russia,country_Saudi Arabia,country_Spain,country_Sweden,country_Switzerland,country_US,country_United Kingdom
0,1,2022-03-02,23,0,2.0,258.0,234.0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,2,2022-03-03,34,1,5.0,645.0,567.0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
5,5,2021-03-23,23,0,1.0,129.0,47.0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7,7,2022-03-08,27,0,2.0,258.0,557.0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
8,8,2021-02-02,23,0,1.0,129.0,455.0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [77]:
any_missing = raw_data.isnull().any().any()
print("هل توجد قيم مفقودة؟", any_missing)# اذا ترو يعني في قيم ناقصة اما فولز يعني مافي
#This line drops the columns customer_id and date from the raw_data DataFrame.
#The inplace=True argument ensures that the changes are applied to the raw_data DataFrame directly (i.e., it modifies the DataFrame in place instead of returning a new one).
#axis=1 means that the operation is applied to columns (axis 0 would apply to rows).
raw_data.drop(["customer_id","date"],inplace=True,axis=1)

# scaler = MinMaxScaler():This line creates an instance of the MinMaxScaler from the sklearn.preprocessing module.
# The Min-Max Scaler transforms features by scaling them to a range of values, typically between 0 and 1. 
# It does this by adjusting the values according to the formula: newX = (x- min)/(max-min)
scaler = MinMaxScaler()
ml_data = scaler.fit_transform(raw_data)

In [79]:
ml_data

array([[0.08695652, 0.        , 0.125     , 0.17458867, 0.29635499,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 1.        , 0.        ],
       [0.56521739, 1.        , 0.5       , 0.52833638, 0.82408875,
        1.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.08695652, 0.        , 0.        , 0.05667276, 0.        ,
        0.        , 0.        , 1.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.26086957, 0.        , 0.125     , 0.17458867, 0.80824089,
        1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.        , 0.        , 0.        ],
       [0.08695652, 0.        , 0.        , 0.05667276, 0.64659271,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 1.        , 0.        ],
       [0.34782609, 1.        , 0.125     , 0.17458867, 0.48878459,
        0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.625     , 0.64625229, 0.80348653,
        1.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.43478261, 1.        , 0.375     , 0.41042048, 0.82408875,
        1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 1.        , 0.        ],
       [0.47826087, 0.        , 0.125     , 0.17458867, 0.47543582,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.26086957, 0.        , 0.25      , 0.29250457, 0.48878459,
        0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.08695652, 1.        , 0.625     , 0.64625229, 0.84786054,
        1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.2173913 , 0.        , 0.75      , 0.76416819, 0.29635499,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.34782609, 1.        , 1.        , 1.        , 0.48878459,
        0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.60869565, 0.        , 0.625     , 0.64625229, 0.68304279,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.73913043, 1.        , 0.125     , 0.17458867, 0.70206022,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 1.        , 0.        ],
       [0.86956522, 0.        , 0.75      , 0.76416819, 0.29635499,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 1.        , 0.        ],
       [1.        , 1.        , 0.5       , 0.52833638, 0.29635499,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.08695652, 0.        , 0.25      , 0.29250457, 1.        ,
        1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 1.        , 0.37068966, 0.        , 0.48878459,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.2173913 , 0.        , 0.375     , 0.41042048, 0.09825674,
        0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.26086957, 0.        , 0.25      , 0.29250457, 0.54358162,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.        ],
       [0.56521739, 0.        , 0.25      , 0.29250457, 0.35023772,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.        , 0.        , 0.        ],
       [0.26086957, 1.        , 0.25      , 0.29250457, 0.29793978,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 1.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ]])